# Generated by Django 5.0.7 on 2025-06-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
