# Generated by Django 5.0.7 on 2025-06-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateagentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagentprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagentprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
