# Generated by Django 5.2.3 on 2025-06-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bankdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotinquiry',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plotinquiry',
            name='lead_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plotinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
