# Generated by Django 5.0.7 on 2025-06-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_realestateagentprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotlisting',
            name='description',
        ),
        migrations.AddField(
            model_name='plotlisting',
            name='plot_file',
            field=models.FileField(blank=True, null=True, upload_to='plot_files/'),
        ),
    ]
