# Generated by Django 5.2.1 on 2025-06-27 07:03

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_plotlisting_description_plotlisting_plot_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLFTProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('plot_type', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('sqft', 'Square Feet'), ('sqyd', 'Square Yards')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('project_layout', models.FileField(blank=True, null=True, upload_to='project_layouts/')),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('project_video', models.FileField(blank=True, null=True, upload_to='project_videos/')),
                ('land_document', models.FileField(blank=True, null=True, upload_to='land_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default=core.models.generate_referral_code, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plot_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.plotlisting')),
            ],
        ),
        migrations.CreateModel(
            name='PlotInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('inquiry', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.plotlisting')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Inactive', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_commissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_commissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
