# Generated by Django 5.2.1 on 2025-06-27 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sqlftproject_customuser_referral_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('area_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='agent_plots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_plots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PlotImage',
        ),
    ]
