# Generated by Django 5.2.1 on 2025-06-27 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agentplot_delete_plotimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('district', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('Plot', 'Plot'), ('Apartment', 'Apartment')], max_length=50)),
                ('unit', models.CharField(choices=[('Sqft', 'Sqft'), ('Acre', 'Acre')], max_length=20)),
                ('sqft_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('layout_pdf', models.FileField(blank=True, null=True, upload_to='microplots/layouts/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='microplots/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='microplots/videos/')),
                ('land_pdf', models.FileField(blank=True, null=True, upload_to='microplots/land/')),
                ('land_docs_pdf', models.FileField(blank=True, null=True, upload_to='microplots/docs/')),
                ('amenities', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
