# Generated by Django 5.2.1 on 2025-06-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_microplot'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentplot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
