# Generated by Django 5.2.1 on 2025-09-09 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_verifiedplot_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotlisting',
            name='area_unit',
            field=models.CharField(choices=[('sqft', 'Square Feet'), ('sqyards', 'Square Yards'), ('cent', 'Cent'), ('acres', 'Acres')], default='sqft', help_text='Unit for area measurement', max_length=10),
        ),
        migrations.AddField(
            model_name='plotlisting',
            name='facing',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('northeast', 'Northeast'), ('northwest', 'Northwest'), ('southeast', 'Southeast'), ('southwest', 'Southwest')], help_text='Direction the plot faces', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plotlisting',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='Google Maps link for live location', null=True),
        ),
        migrations.AddField(
            model_name='plotlisting',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Plot image 1', null=True, upload_to='plot_images/'),
        ),
        migrations.AddField(
            model_name='plotlisting',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Plot image 2', null=True, upload_to='plot_images/'),
        ),
        migrations.AddField(
            model_name='plotlisting',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Plot image 3', null=True, upload_to='plot_images/'),
        ),
        migrations.AddField(
            model_name='plotlisting',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Plot image 4', null=True, upload_to='plot_images/'),
        ),
        migrations.AddField(
            model_name='plotlisting',
            name='image_5',
            field=models.ImageField(blank=True, help_text='Plot image 5', null=True, upload_to='plot_images/'),
        ),
        migrations.AddField(
            model_name='plotlisting',
            name='plot_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('farms', 'Farms'), ('commercial', 'Commercial')], default='residential', help_text='Type of plot', max_length=20),
        ),
        migrations.AddField(
            model_name='plotlisting',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit (sqft/sqyards/cent/acres)', max_digits=10),
        ),
        migrations.AddField(
            model_name='plotlisting',
            name='survey_number',
            field=models.CharField(blank=True, help_text='Survey number of the plot', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotlisting',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total area of the plot', max_digits=10),
        ),
        migrations.AlterField(
            model_name='plotlisting',
            name='plot_file',
            field=models.FileField(blank=True, help_text='Plot document file', null=True, upload_to='plot_files/'),
        ),
        migrations.AlterField(
            model_name='plotlisting',
            name='price_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per square foot (legacy)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plotlisting',
            name='total_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total area in square feet (legacy)', max_digits=10, null=True),
        ),
    ]
